apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10536252-ca-frontend
spec:
  replicas: 2 
  selector:
    matchLabels:
      deployment-name: 10536252-ca-frontend
  template:
    metadata:
      labels:
        deployment-name: 10536252-ca-frontend
    spec:
      containers:
      - name: ca-frontend-container
        image: 10536252/ca-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
   service-label: ca-frontend-cluster-service
  name: ca-frontend-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ca-frontend-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ca-frontend-cluster-service
  name: application-frontend-cluster-service-loadbalancer
spec: 
  type: LoadBalancer
  ports:
  - name: ca-frontend-load-balancer-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10536252-ca-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      deployment-name: 10536252-ca-api
  template:
    metadata:
      labels:
        deployment-name: 10536252-ca-api
    spec:
      containers:
      - name: ca-frontend-container
        image: 10536252/ca-api:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
   service-label: ca-frontend-cluster-service
  name: ca-frontend-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ca-api-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ca-frontend-cluster-service
  name: application-frontend-cluster-service-loadbalancer
spec: 
  type: LoadBalancer
  ports:
  - name: ca-frontend-load-balancer-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-api


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: 10536252-ca-mongo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: 10536252-ca-mongo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: 10536252-ca-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
   service-label: ca-backend-cluster-service
  name: ca-frontend-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ca-backend-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ca-backend-cluster-service
  name: application-frontend-cluster-service-loadbalancer
spec: 
  type: LoadBalancer
  ports:
  - name: ca-frontend-load-balancer-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-mongo

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ca-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ca-frontend
  minReplicas: 1
  maxReplicas: 10
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
